### ISSUE TITLE
Stop cover command has disappeard after updating

### ISSUE THREAD

**Issue by thommio** [jseyster/esphome-rts-control#1]
Stop cover command has disappeard after updating ESPhome and RTS control add on. Anyone else experiencing this?

**Comment by jseyster** [comment]
Thanks for the heads up! It looks like ESPHome previously assumed that all "cover" entities have a "stop" action, but has now added an explicit "supports stop" trait that is false by default. It should be as simple as adding `traits.set_supports_stop(true);` to `RTSCover::get_traits()`, but it might be a few days until I have time to properly test it.

**Comment by jseyster** [comment]
Nice! Adding the "supports stop" trait worked on the first try. Let me know if you hit any issues with the upgrade @thommio.

**Comment by thommio** [comment]
That worked for me, great work :)
